name: Build Android APK and Generate Documentation
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Godot
        run: |
          wget https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot_v4.3-stable_linux.x86_64.zip
          chmod +x Godot_v4.3-stable_linux.x86_64
          mv Godot_v4.3-stable_linux.x86_64 godot
      - name: Build Android APK
        run: |
          if [ ! -f export_presets.cfg ]; then
            echo "export_presets.cfg manquant. Création d’un preset par défaut..."
            ./godot --headless --script res://create_export_preset.gd
          fi
          chmod -R u+w .
          ./godot --headless --export-debug "Android" build/android.apk
        working-directory: .
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/android.apk
      - name: Generate Documentation
        run: |
          ./godot --path . --script res://generate_docs.gd
        working-directory: .
      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: doc/documentation.md
